spring.application.name=nestbites
spring.data.mongodb.database=nestbites
jwt.secret=NestBitesSecretKey2026VerySecureKeyNestBites123456
jwt.expiration=604800000
server.port=8081
razorpay.key.id=YOUR_RAZORPAY_KEY_ID
razorpay.key.secret=YOUR_RAZORPAY_KEY_SECRET
cloudinary.cloud-name=ww2rekjv
cloudinary.api-key=486621917995767
cloudinary.api-secret=6F3YmYECtWDvIGRiDgt7iX57ovc