spring.application.name=NestBites

# ==========================
# Server
# ==========================
server.port=8081

# ==========================
# MongoDB
# ==========================
spring.data.mongodb.uri=mongodb://localhost:27017/nestbites

# ==========================
# JWT
# ==========================
jwt.secret=NestBitesSecretKey2026VerySecureKeyNestBites123456
jwt.expiration=604800000

# ==========================
# Razorpay
# ==========================
razorpay.key.id=YOUR_RAZORPAY_KEY_ID
razorpay.key.secret=YOUR_RAZORPAY_KEY_SECRET

# ==========================
# Cloudinary
# ==========================
cloudinary.cloud-name=YOUR_CLOUD_NAME
cloudinary.api-key=YOUR_API_KEY
cloudinary.api-secret=YOUR_API_SECRET

# ==========================
# Swagger
# ==========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==========================
# Actuator
# ==========================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

# ==========================
# Logging
# ==========================
logging.level.org.springframework=INFO
logging.level.homies.com.backend=DEBUG